name = "parrot"
version = "0.0.13"

description = "ğŸ¦œ type-safe SQL in gleam for sqlite, postgresql & mysql"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "parrot" }

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
given = ">= 5.0.4 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
