name = "parrot"
version = "2.1.3"

description = "ğŸ¦œ type-safe SQL in gleam for sqlite, postgresql & mysql"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "parrot" }

target = "erlang"

[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
  { title = "TOML reference", path = "toml-reference.html", source = "./pages/toml-reference.md" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
glearray = ">= 2.1.0 and < 3.0.0"
repeatedly = ">= 2.1.2 and < 3.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
choire = ">= 1.0.7 and < 2.0.0"
